create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  service text,
  budget text,
  message text not null,
  created_at timestamptz not null default now()
);

-- يضيف العمود للمشروعات التي أنشأت الجدول بإصدار أقدم من الملف.
alter table public.contact_messages
  add column if not exists budget text;

create index if not exists idx_contact_messages_email
  on public.contact_messages (email);

create index if not exists idx_contact_messages_created_at
  on public.contact_messages (created_at desc);

alter table public.contact_messages enable row level security;

-- يسمح لنموذج الموقع بالإضافة فقط، مع تحقق أساسي من القيم.
drop policy if exists "Allow public insert to contact_messages"
  on public.contact_messages;

create policy "Allow public insert to contact_messages"
on public.contact_messages
for insert
to anon, authenticated
with check (
  char_length(trim(name)) between 2 and 100
  and char_length(trim(email)) between 5 and 254
  and position('@' in email) > 1
  and char_length(trim(message)) between 10 and 5000
  and (phone is null or char_length(trim(phone)) <= 30)
);

-- لا يجب أن يتمكن أي زائر من قراءة رسائل العملاء من المتصفح.
drop policy if exists "Allow public read of contact_messages"
  on public.contact_messages;

-- القراءة متاحة لأدوار الإدارة والمالك والدعم.
drop policy if exists "Allow admins to read contact_messages"
  on public.contact_messages;

create policy "Allow admins to read contact_messages"
on public.contact_messages
for select
to authenticated
using (
  ((select auth.jwt()) -> 'app_metadata' ->> 'role') in ('owner', 'admin', 'support')
);

revoke all on table public.contact_messages from anon, authenticated;
grant insert on table public.contact_messages to anon, authenticated;
grant select on table public.contact_messages to authenticated;
grant usage, select on sequence public.contact_messages_id_seq
  to anon, authenticated;

-- بعد إنشاء مستخدم الإدارة من Authentication > Users، نفّذ الأمر التالي بعد
-- استبدال البريد، ويفضل قبل أول تسجيل دخول حتى تتضمن الجلسة دور admin:
-- update auth.users
-- set raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb)
--   || '{"role":"admin"}'::jsonb
-- where email = 'admin@example.com';

-- يستطيع Django أيضاً القراءة باستخدام اتصال PostgreSQL آمن أو مفتاح
-- Supabase secret محفوظ على الخادم فقط، ولا يوضع أي منهما داخل الواجهة.

-- مثال إدخال:
-- insert into public.contact_messages (name, email, phone, service, budget, message)
-- values ('أحمد محمد', 'ahmed@example.com', '01000000000', 'تطوير موقع', '5,000 - 15,000', 'أرغب في تصميم موقع متكامل');

-- مثال عرض كل الرسائل من SQL Editor أو Django:
-- select * from public.contact_messages order by created_at desc;
