-- جدول المشتركين في النشرة البريدية
create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null,
  source text not null default 'website_footer',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unsubscribed_at timestamptz,
  constraint newsletter_subscribers_email_format check (
    email = lower(trim(email))
    and char_length(email) between 5 and 254
    and position('@' in email) > 1
  ),
  constraint newsletter_subscribers_source_length check (
    char_length(trim(source)) between 1 and 50
  )
);

-- يمنع تسجيل البريد نفسه أكثر من مرة، حتى لو اختلفت حالة الأحرف.
create unique index if not exists idx_newsletter_subscribers_email
  on public.newsletter_subscribers (lower(email));

create index if not exists idx_newsletter_subscribers_created_at
  on public.newsletter_subscribers (created_at desc);

alter table public.newsletter_subscribers enable row level security;

-- زائر الموقع يستطيع إضافة اشتراك فقط، ولا يستطيع قراءة القائمة.
drop policy if exists "Allow public newsletter subscriptions"
  on public.newsletter_subscribers;

create policy "Allow public newsletter subscriptions"
on public.newsletter_subscribers
for insert
to anon, authenticated
with check (
  email = lower(trim(email))
  and char_length(email) between 5 and 254
  and position('@' in email) > 1
  and source = 'website_footer'
  and is_active = true
  and unsubscribed_at is null
);

-- الأدوار المصرح لها داخل لوحة Awexen تستطيع قراءة المشتركين.
drop policy if exists "Allow admins to read newsletter subscribers"
  on public.newsletter_subscribers;

create policy "Allow admins to read newsletter subscribers"
on public.newsletter_subscribers
for select
to authenticated
using (
  ((select auth.jwt()) -> 'app_metadata' ->> 'role')
    in ('owner', 'admin', 'editor', 'support')
);

-- الإدارة والدعم يمكنهما تحديث حالة الاشتراك عند إضافة زر إلغاء الاشتراك.
drop policy if exists "Allow admins to update newsletter subscribers"
  on public.newsletter_subscribers;

create policy "Allow admins to update newsletter subscribers"
on public.newsletter_subscribers
for update
to authenticated
using (
  ((select auth.jwt()) -> 'app_metadata' ->> 'role')
    in ('owner', 'admin', 'support')
)
with check (
  ((select auth.jwt()) -> 'app_metadata' ->> 'role')
    in ('owner', 'admin', 'support')
);

-- الحذف متاح للمالك والإدارة فقط.
drop policy if exists "Allow admins to delete newsletter subscribers"
  on public.newsletter_subscribers;

create policy "Allow admins to delete newsletter subscribers"
on public.newsletter_subscribers
for delete
to authenticated
using (
  ((select auth.jwt()) -> 'app_metadata' ->> 'role')
    in ('owner', 'admin')
);

revoke all on table public.newsletter_subscribers from anon, authenticated;
grant insert on table public.newsletter_subscribers to anon, authenticated;
grant select, update, delete on table public.newsletter_subscribers to authenticated;
grant usage, select on sequence public.newsletter_subscribers_id_seq
  to anon, authenticated;

comment on table public.newsletter_subscribers is
  'Newsletter subscriptions submitted from the Awexen website.';

-- اختبار بعد التنفيذ:
-- select id, email, source, is_active, created_at
-- from public.newsletter_subscribers
-- order by created_at desc;
