import type { ResourceDefinition } from "./types";

const publishOptions = [
  { label: "مسودة", value: "draft" },
  { label: "منشور", value: "published" },
  { label: "مؤرشف", value: "archived" },
];

export const resources = {
  pages: {
    table: "content_pages",
    title: "الصفحات",
    singular: "صفحة",
    description: "أنشئ صفحة جديدة أو عدّل النص وبيانات الظهور في البحث. رابط الصفحة يكون /pages/slug.",
    titleKey: "title",
    subtitleKey: "slug",
    statusKey: "status",
    orderBy: "sort_order",
    defaults: { slug: "", title: "", page_type: "custom", status: "draft", excerpt: "", body: "", seo_title: "", seo_description: "", featured_image: "", sort_order: 0 },
    fields: [
      { key: "title", label: "عنوان الصفحة", required: true },
      { key: "slug", label: "الرابط المختصر بالإنجليزية", required: true, placeholder: "company-profile" },
      { key: "page_type", label: "نوع الصفحة", type: "select", options: [
        { label: "صفحة عادية", value: "custom" }, { label: "Landing page", value: "landing" },
        { label: "قانونية", value: "legal" }, { label: "أساسية", value: "system" },
      ] },
      { key: "status", label: "الحالة", type: "select", options: publishOptions },
      { key: "excerpt", label: "الوصف المختصر", type: "textarea", wide: true },
      { key: "body", label: "محتوى الصفحة", type: "textarea", required: true, wide: true },
      { key: "featured_image", label: "رابط الصورة البارزة", type: "url", nullable: true, wide: true },
      { key: "seo_title", label: "عنوان SEO", wide: true },
      { key: "seo_description", label: "وصف SEO", type: "textarea", wide: true },
      { key: "sort_order", label: "الترتيب", type: "number" },
    ],
  },
  blog: {
    table: "blog_posts",
    title: "المدونة",
    singular: "مقال",
    description: "مقالات عملية باسم الكاتب وتصنيف واضح، مع عنوان ووصف مستقلين لمحركات البحث.",
    titleKey: "title",
    subtitleKey: "category",
    statusKey: "status",
    orderBy: "published_at",
    defaults: { slug: "", title: "", excerpt: "", content: "", category: "أعمال رقمية", author_name: "فريق Awexen", featured_image: "", status: "draft", seo_title: "", seo_description: "", published_at: "" },
    fields: [
      { key: "title", label: "عنوان المقال", required: true, wide: true },
      { key: "slug", label: "الرابط المختصر بالإنجليزية", required: true, placeholder: "website-speed-guide" },
      { key: "category", label: "التصنيف", required: true },
      { key: "author_name", label: "اسم الكاتب", required: true },
      { key: "status", label: "الحالة", type: "select", options: publishOptions },
      { key: "published_at", label: "موعد النشر", type: "datetime-local", nullable: true },
      { key: "excerpt", label: "مقدمة مختصرة", type: "textarea", required: true, wide: true },
      { key: "content", label: "محتوى المقال", type: "textarea", required: true, wide: true },
      { key: "featured_image", label: "رابط الصورة", type: "url", nullable: true, wide: true },
      { key: "seo_title", label: "عنوان SEO", wide: true },
      { key: "seo_description", label: "وصف SEO", type: "textarea", wide: true },
    ],
  },
  jobs: {
    table: "jobs",
    title: "الوظائف",
    singular: "وظيفة",
    description: "انشر الدور والمتطلبات ثم تابع المتقدمين من قسم طلبات التوظيف.",
    titleKey: "title",
    subtitleKey: "department",
    statusKey: "status",
    defaults: { slug: "", title: "", department: "التطوير", employment_type: "full-time", location: "عن بُعد", summary: "", requirements: "", responsibilities: "", status: "draft", closes_at: "" },
    fields: [
      { key: "title", label: "المسمى الوظيفي", required: true },
      { key: "slug", label: "الرابط المختصر", required: true, placeholder: "frontend-developer" },
      { key: "department", label: "القسم", required: true },
      { key: "employment_type", label: "نظام العمل", type: "select", options: [
        { label: "دوام كامل", value: "full-time" }, { label: "دوام جزئي", value: "part-time" },
        { label: "تعاقد", value: "contract" }, { label: "تدريب", value: "internship" }, { label: "عمل حر", value: "freelance" },
      ] },
      { key: "location", label: "المكان", required: true },
      { key: "status", label: "الحالة", type: "select", options: [
        { label: "مسودة", value: "draft" }, { label: "منشورة", value: "published" }, { label: "مغلقة", value: "closed" },
      ] },
      { key: "closes_at", label: "آخر موعد", type: "date", nullable: true },
      { key: "summary", label: "ملخص الوظيفة", type: "textarea", required: true, wide: true },
      { key: "responsibilities", label: "المهام — كل نقطة في سطر", type: "textarea", wide: true },
      { key: "requirements", label: "المتطلبات — كل نقطة في سطر", type: "textarea", wide: true },
    ],
  },
  courses: {
    table: "courses",
    title: "الكورسات",
    singular: "كورس",
    description: "أضف البرامج التدريبية وحدد السعر والموعد والسعة وطريقة الحضور.",
    titleKey: "title",
    subtitleKey: "instructor",
    statusKey: "status",
    orderBy: "starts_at",
    defaults: { slug: "", title: "", short_description: "", description: "", instructor: "فريق Awexen", delivery_mode: "online", level: "beginner", duration: "", price: 1500, currency: "جنيه", capacity: "", starts_at: "", featured_image: "", status: "draft" },
    fields: [
      { key: "title", label: "اسم الكورس", required: true },
      { key: "slug", label: "الرابط المختصر", required: true, placeholder: "frontend-foundations" },
      { key: "instructor", label: "المحاضر", required: true },
      { key: "duration", label: "المدة", placeholder: "8 أسابيع" },
      { key: "delivery_mode", label: "طريقة التقديم", type: "select", options: [
        { label: "أونلاين مباشر", value: "online" }, { label: "حضوري", value: "onsite" }, { label: "هجين", value: "hybrid" }, { label: "مسجل", value: "recorded" },
      ] },
      { key: "level", label: "المستوى", type: "select", options: [
        { label: "مبتدئ", value: "beginner" }, { label: "متوسط", value: "intermediate" }, { label: "متقدم", value: "advanced" }, { label: "كل المستويات", value: "all-levels" },
      ] },
      { key: "price", label: "السعر", type: "number", required: true, min: 1 },
      { key: "currency", label: "العملة" },
      { key: "capacity", label: "عدد المقاعد", type: "number", nullable: true },
      { key: "starts_at", label: "موعد البداية", type: "datetime-local", nullable: true },
      { key: "status", label: "الحالة", type: "select", options: [
        { label: "مسودة", value: "draft" }, { label: "منشور", value: "published" }, { label: "مغلق", value: "closed" },
      ] },
      { key: "short_description", label: "الوصف المختصر", type: "textarea", required: true, wide: true },
      { key: "description", label: "تفاصيل الكورس", type: "textarea", required: true, wide: true },
      { key: "featured_image", label: "رابط الصورة", type: "url", nullable: true, wide: true },
    ],
  },
  clients: {
    table: "clients",
    title: "العملاء",
    singular: "عميل",
    description: "سجل موحد للعميل، المرحلة الحالية، قيمة المشروع والمدفوع والمتابعة التالية.",
    titleKey: "name",
    subtitleKey: "company",
    statusKey: "stage",
    orderBy: "next_follow_up",
    defaults: { name: "", company: "", email: "", phone: "", source: "manual", stage: "lead", service: "", project_value: 0, paid_value: 0, next_follow_up: "", notes: "" },
    fields: [
      { key: "name", label: "اسم العميل", required: true },
      { key: "company", label: "الشركة" },
      { key: "email", label: "البريد الإلكتروني" },
      { key: "phone", label: "الهاتف" },
      { key: "source", label: "مصدر العميل", placeholder: "تواصل / إحالة / حملة" },
      { key: "service", label: "الخدمة" },
      { key: "stage", label: "مرحلة العميل", type: "select", options: [
        { label: "Lead", value: "lead" }, { label: "مؤهل", value: "qualified" }, { label: "عرض سعر", value: "proposal" },
        { label: "مشروع نشط", value: "active" }, { label: "مكتمل", value: "completed" }, { label: "غير مكتمل", value: "lost" },
      ] },
      { key: "next_follow_up", label: "المتابعة القادمة", type: "date", nullable: true },
      { key: "project_value", label: "قيمة المشروع", type: "number" },
      { key: "paid_value", label: "المبلغ المدفوع", type: "number" },
      { key: "notes", label: "ملاحظات العميل", type: "textarea", wide: true },
    ],
  },
  knowledge: {
    table: "ai_knowledge",
    title: "قاعدة معرفة AI",
    singular: "مصدر معرفة",
    description: "الإجابات المنشورة هنا هي المصدر الوحيد لعنصر محادثة «اسأل Awexen» الآن وللـAgent لاحقًا.",
    titleKey: "title",
    subtitleKey: "topic",
    statusKey: "status",
    orderBy: "priority",
    defaults: { title: "", topic: "عام", question: "", answer: "", source_type: "manual", source_url: "", status: "draft", priority: 0 },
    fields: [
      { key: "title", label: "عنوان داخلي", required: true },
      { key: "topic", label: "الموضوع", required: true },
      { key: "status", label: "الحالة", type: "select", options: publishOptions },
      { key: "priority", label: "الأولوية", type: "number" },
      { key: "question", label: "صيغة سؤال متوقعة", type: "textarea", wide: true },
      { key: "answer", label: "الإجابة المعتمدة", type: "textarea", required: true, wide: true },
      { key: "source_type", label: "نوع المصدر", type: "select", options: [
        { label: "محتوى يدوي", value: "manual" }, { label: "مصدر خارجي", value: "url" }, { label: "ملف PDF", value: "pdf" },
      ] },
      { key: "source_url", label: "رابط المصدر الخارجي — اختياري", type: "url", nullable: true, wide: true },
    ],
  },
} satisfies Record<string, ResourceDefinition>;
