# Generated by Django 5.2.5 on 2026-08-25 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def secure_booking_storage(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE public.commerce_coursebooking ENABLE ROW LEVEL SECURITY")
        cursor.execute("REVOKE ALL PRIVILEGES ON TABLE public.commerce_coursebooking FROM anon, authenticated")
        cursor.execute("SELECT to_regclass('storage.objects')")
        if cursor.fetchone()[0] is None:
            return
        cursor.execute(
            """
            INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
            VALUES (
                'payment-proofs', 'payment-proofs', false, 5242880,
                ARRAY['image/jpeg', 'image/png', 'application/pdf']
            )
            ON CONFLICT (id) DO UPDATE SET
                public = EXCLUDED.public,
                file_size_limit = EXCLUDED.file_size_limit,
                allowed_mime_types = EXCLUDED.allowed_mime_types
            """
        )
        cursor.execute('DROP POLICY IF EXISTS "Learners upload own payment proofs" ON storage.objects')
        cursor.execute(
            """
            CREATE POLICY "Learners upload own payment proofs" ON storage.objects
            FOR INSERT TO authenticated
            WITH CHECK (
                bucket_id = 'payment-proofs'
                AND (storage.foldername(name))[1] = (SELECT auth.uid())::text
            )
            """
        )
        cursor.execute('DROP POLICY IF EXISTS "Learners and admins read payment proofs" ON storage.objects')
        cursor.execute(
            """
            CREATE POLICY "Learners and admins read payment proofs" ON storage.objects
            FOR SELECT TO authenticated
            USING (
                bucket_id = 'payment-proofs'
                AND (
                    (storage.foldername(name))[1] = (SELECT auth.uid())::text
                    OR COALESCE((SELECT auth.jwt()) -> 'app_metadata' ->> 'role', '')
                        IN ('owner', 'admin', 'editor', 'support')
                )
            )
            """
        )
        cursor.execute('DROP POLICY IF EXISTS "Learners replace own payment proofs" ON storage.objects')
        cursor.execute(
            """
            CREATE POLICY "Learners replace own payment proofs" ON storage.objects
            FOR UPDATE TO authenticated
            USING (
                bucket_id = 'payment-proofs'
                AND (storage.foldername(name))[1] = (SELECT auth.uid())::text
            )
            WITH CHECK (
                bucket_id = 'payment-proofs'
                AND (storage.foldername(name))[1] = (SELECT auth.uid())::text
            )
            """
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_capacity_course_currency_course_delivery_mode_and_more'),
        ('learning', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('payment_submitted', 'Payment submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='awaiting_payment', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EGP', max_length=8)),
                ('payment_method', models.CharField(blank=True, choices=[('instapay', 'InstaPay'), ('vodafone_cash', 'Vodafone Cash')], max_length=24)),
                ('payment_phone', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('experience_level', models.CharField(blank=True, max_length=120)),
                ('goal', models.TextField(blank=True)),
                ('proof_path', models.CharField(blank=True, max_length=500)),
                ('proof_content_type', models.CharField(blank=True, max_length=120)),
                ('proof_size', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('course_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='courses.courseversion')),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='learning.enrollment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_bookings', to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_course_bookings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'status', 'created_at'], name='commerce_co_organiz_93b8dc_idx'), models.Index(fields=['user', 'status', 'created_at'], name='commerce_co_user_id_654fbe_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'course_version'), name='unique_booking_per_user_version'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='booking_amount_not_negative')],
            },
        ),
        migrations.RunPython(secure_booking_storage, reverse_code=migrations.RunPython.noop),
    ]
