# Generated by Django 5.2.5 on 2026-08-25 09:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=160)),
                ('title', models.CharField(max_length=240)),
                ('short_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='organizations.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CourseVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('title', models.CharField(max_length=240)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(default='ar', max_length=12)),
                ('difficulty', models.CharField(default='all_levels', max_length=32)),
                ('estimated_minutes', models.PositiveIntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('learning_outcomes', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('target_audience', models.TextField(blank=True)),
                ('change_notes', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_course_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-version_number',),
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_lead', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_assignments', to=settings.AUTH_USER_MODEL)),
                ('course_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='courses.courseversion')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_courses', to='courses.courseversion'),
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('timezone', models.CharField(default='Africa/Cairo', max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='organizations.organization')),
                ('course_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='courses.courseversion')),
            ],
            options={
                'ordering': ('-starts_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('course_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.courseversion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('presentation', 'Presentation'), ('external_url', 'External URL'), ('live', 'Live session')], default='text', max_length=24)),
                ('video_url', models.URLField(blank=True)),
                ('resource_url', models.URLField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=7)),
                ('completion_rule', models.CharField(choices=[('manual', 'Manual completion'), ('view', 'Complete on view'), ('video_threshold', 'Video threshold')], default='manual', max_length=24)),
                ('completion_threshold', models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_lessons', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='courseversion',
            constraint=models.UniqueConstraint(fields=('course', 'version_number'), name='unique_course_version_number'),
        ),
        migrations.AddConstraint(
            model_name='courseinstructor',
            constraint=models.UniqueConstraint(fields=('course_version', 'instructor'), name='unique_instructor_per_course_version'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='courses_cou_organiz_395158_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_course_slug_per_org'),
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['organization', 'status', 'starts_at'], name='courses_coh_organiz_50918d_idx'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course_version', 'sort_order'), name='unique_module_order_per_version'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'sort_order'), name='unique_lesson_order_per_module'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='lesson_weight_must_be_positive'),
        ),
    ]
