# Generated by Django 5.2.5 on 2026-08-25 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(default='EGP', max_length=8),
        ),
        migrations.AddField(
            model_name='course',
            name='delivery_mode',
            field=models.CharField(choices=[('recorded', 'Recorded'), ('online', 'Live online'), ('onsite', 'On site'), ('hybrid', 'Hybrid')], default='recorded', max_length=16),
        ),
        migrations.AddField(
            model_name='course',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='course',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseversion',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courseversion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseversion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_course_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseversion',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
