-- أنواع مشاريع معرض الأعمال:Classification قائمة يملؤها الأداري.
-- الحقل category_ar بقى drop-down يقرأ من الجدول ده بدل نص حر.
create table if not exists public.portfolio_categories (
  id bigint generated by default as identity primary key,
  label_ar text not null,
  label_en text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_portfolio_categories_label_ar
  on public.portfolio_categories (label_ar);

alter table public.portfolio_categories enable row level security;

-- الأداريين بس بيملوا القائمة. الزوار ميقدروش يقراها.
--
-- ملاحظة: بنفحص الدور من الـ JWT مباشرة بدل ما ننداء public.has_awexen_role،
-- لأن الدالة دي مش مضمونة إنها متعملة على كل قواعد البيانات. نفس النمط
-- اللي شغّال في سياسة contact_messages.
drop policy if exists "admins manage portfolio categories" on public.portfolio_categories;

create policy "admins manage portfolio categories"
on public.portfolio_categories
for all to authenticated
using (((select auth.jwt()) -> 'app_metadata' ->> 'role') in ('owner','admin','editor'))
with check (((select auth.jwt()) -> 'app_metadata' ->> 'role') in ('owner','admin','editor'));

grant select on public.portfolio_categories to anon, authenticated;
grant insert, update, delete on public.portfolio_categories to authenticated;
grant usage, select on sequence public.portfolio_categories_id_seq to authenticated;

-- قيم مبدئية: الأنواع الشائعة في سوق العمل العربي.
-- sort_order بيحدد ترتيب ظهورها في الدروب داون.
insert into public.portfolio_categories (label_ar, label_en, sort_order) values
  ('متجر إلكتروني', 'E-commerce', 10),
  ('منصة تعليمية', 'Educational Platform', 20),
  ('موقع تعريفي', 'Corporate Website', 30),
  ('موقع خدمات', 'Services Website', 40),
  ('تطبيق موبايل', 'Mobile App', 50),
  ('لوحة تحكم', 'Admin Dashboard', 60),
  ('نظام حجوزات', 'Booking System', 70),
  ('مدونة', 'Blog', 80),
  ('هوية بصرية', 'Brand Identity', 90),
  ('تصميم واجهات', 'UI/UX Design', 100),
  ('تسويق رقمي', 'Digital Marketing', 110),
  ('مشروع رقمي', 'Digital Project', 120)
on conflict (label_ar) do nothing;