-- أنواع مشاريع معرض الأعمال:Classification قائمة يملؤها الأداري.
-- الحقل category_ar بقى drop-down يقرأ من الجدول ده بدل نص حر.
create table if not exists public.portfolio_categories (
  id bigint generated by default as identity primary key,
  label_ar text not null,
  label_en text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_portfolio_categories_label_ar
  on public.portfolio_categories (label_ar);

alter table public.portfolio_categories enable row level security;

-- الأداريين بس بيملوا القائمة. الزوار ميقدروش يقراها.
drop policy if exists "admins manage portfolio categories" on public.portfolio_categories;

create policy "admins manage portfolio categories"
on public.portfolio_categories
for all to authenticated
using (public.has_awexen_role(array['owner','admin','editor']))
with check (public.has_awexen_role(array['owner','admin','editor']));

grant select on public.portfolio_categories to anon, authenticated;
grant insert, update, delete on public.portfolio_categories to authenticated;
grant usage, select on sequence public.portfolio_categories_id_seq to authenticated;

-- قيم مبدئية: نفس التصنيفات اللي الموقع بيستخدمها دلوقتي.
insert into public.portfolio_categories (label_ar, label_en, sort_order) values
  ('مشروع رقمي', 'Digital Project', 10),
  ('متجر إلكتروني', 'E-commerce', 20),
  ('موقع تعريفي', 'Corporate Site', 30),
  ('تطبيق موبايل', 'Mobile App', 40),
  ('هوية بصرية', 'Brand Identity', 50)
on conflict (label_ar) do nothing;