-- طلبات عرض السعر من صفحة /quote العامة.
--
-- نفس نموذج الوصول بتاع contact_messages: الزائر يُدرج فقط، والإدارة
-- تقرأ وتعدّل وتحذف. كل تفاصيل المشروع أعمدة nullable عشان الفورم
-- يتطوّر من غير migration لكل سؤال جديد.
--
-- idempotent: ينفع يتنفذ على قاعدة فيها الجدول من قبل.

create table if not exists public.quote_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  project_type text,
  industry text,
  current_site text,
  goals text not null,
  pages text,
  languages text,
  design_style text,
  colors text,
  logo text,
  content_ready text,
  products text,
  payments text,
  features text,
  hosting text,
  domain text,
  seo text,
  analytics text,
  maintenance text,
  timeline text,
  budget text,
  reference text,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_quote_requests_created_at
  on public.quote_requests (created_at desc);

create index if not exists idx_quote_requests_email
  on public.quote_requests (email);

alter table public.quote_requests enable row level security;

-- الزائر يُدرج فقط، مع تحقق أساسي من القيم.
drop policy if exists "Allow public insert to quote_requests"
  on public.quote_requests;

create policy "Allow public insert to quote_requests"
on public.quote_requests
for insert
to anon, authenticated
with check (
  char_length(trim(name)) between 2 and 100
  and char_length(trim(email)) between 5 and 254
  and position('@' in email) > 1
  and char_length(trim(goals)) between 10 and 2000
  and (phone is null or char_length(trim(phone)) <= 30)
);

-- بيانات العميل ما تتفreadش من المتصفح أبدًا.
drop policy if exists "Allow public read of quote_requests"
  on public.quote_requests;

drop policy if exists "Allow admins to read quote_requests"
  on public.quote_requests;

create policy "Allow admins to read quote_requests"
on public.quote_requests
for select
to authenticated
using (public.lms_can_review_payments());

-- الإدارة تقدر تعدّل الحالة وملاحظاتها وتكتب عرض السعر.
drop policy if exists "Allow admins to update quote_requests"
  on public.quote_requests;

create policy "Allow admins to update quote_requests"
on public.quote_requests
for update
to authenticated
using (public.lms_can_review_payments())
with check (public.lms_can_review_payments());

-- الإدارة تحذف الطلب بعد التعامل معه.
drop policy if exists "Allow admins to delete quote_requests"
  on public.quote_requests;

create policy "Allow admins to delete quote_requests"
on public.quote_requests
for delete
to authenticated
using (public.lms_can_review_payments());

-- الزائر يُدرج فقط؛ لا قراءة ولا تعديل ولا حذف.
revoke all on table public.quote_requests from anon, authenticated;
grant insert on table public.quote_requests to anon, authenticated;
grant select, update, delete on table public.quote_requests to authenticated;
grant usage, select on sequence public.quote_requests_id_seq
  to anon, authenticated;

-- ---------------------------------------------------------------------------
-- أعمدة اللوحة: الحالة، عرض السعر، الملاحظات، تاريخ التحديث.
-- add column if not exists عشان ينفع يتنفذ على جدول موجود من قبل.
-- ---------------------------------------------------------------------------
alter table public.quote_requests
  add column if not exists status text not null default 'new';

alter table public.quote_requests
  add column if not exists admin_notes text;

alter table public.quote_requests
  add column if not exists quoted_amount numeric(14, 2);

alter table public.quote_requests
  add column if not exists quote_sent_at timestamptz;

alter table public.quote_requests
  add column if not exists updated_at timestamptz not null default now();

create index if not exists idx_quote_requests_status
  on public.quote_requests (status, created_at desc);

-- ---------------------------------------------------------------------------
-- إعدادات التطبيق: مغلقة على anon و authenticated، والمستخدم postgres بس.
-- بنخلي رابط مزود البريد هنا بدل ما يتحط في كود الواجهة.
--
-- ملاحظة: trigger الإيميل نفسه مش متعمل في الـ migration ده عن قصد،
-- لأن رابط المزود سر وغير متاح وقت النشر. خطوات التفعيل موجودة في
-- backend/sql/contact_messages_table.sql.
-- ---------------------------------------------------------------------------
create schema if not exists global;

create table if not exists global.app_settings (
  key text primary key,
  value text,
  updated_at timestamptz not null default now()
);

comment on table global.app_settings is
  'App-wide settings kept out of the browser bundle. RLS is on and no policy grants access to anon or authenticated, so only postgres reads it.';

alter table global.app_settings enable row level security;

revoke all on table global.app_settings from anon, authenticated;